const express = require('express');
const router = express.Router();

// Mock Groq API responses for development
const MOCK_RESPONSES = {
  health: { status: 'healthy', message: 'Groq API is available' },
  explain: {
    response: "This is a mock explanation. In production, this would be generated by Groq AI.",
    explanation: "Mock AI response for code explanation."
  },
  chat: {
    response: "Hello! I'm a mock AI assistant. The real Groq AI would provide intelligent responses here.",
    choices: [{
      message: {
        content: "Mock AI response for chat functionality."
      }
    }]
  }
};

// GET /api/groq/health - Health check
router.get('/health', (req, res) => {
  res.json(MOCK_RESPONSES.health);
});

// POST /api/groq - Main Groq API endpoint
router.post('/', async (req, res) => {
  try {
    const { messages, code, language, model, responseStyle } = req.body;

    // Check if Groq API key is configured
    const groqApiKey = process.env.GROQ_API_KEY;

    if (!groqApiKey || groqApiKey === 'your_groq_api_key_here') {
      // Return mock response if no API key
      let mockResponse;

      if (code && language) {
        // Code explanation request
        mockResponse = {
          response: `Mock AI Explanation for ${language.toUpperCase()} code:\n\n${code}\n\nThis is a placeholder response. Configure GROQ_API_KEY in your .env file to get real AI responses.`,
          explanation: `Mock explanation for ${language} code.`
        };
      } else if (messages) {
        // Chat request
        mockResponse = {
          response: "Mock AI Response: Configure GROQ_API_KEY to enable real AI chat functionality.",
          choices: [{
            message: {
              content: "Mock AI chat response. Add your Groq API key to get intelligent responses."
            }
          }]
        };
      } else {
        mockResponse = {
          response: "Mock AI Response: No API key configured.",
          error: "GROQ_API_KEY not configured"
        };
      }

      return res.json(mockResponse);
    }

    // Real Groq API integration
    const Groq = require('groq-sdk');
    const groq = new Groq({
      apiKey: groqApiKey,
    });

    let response;

    if (code && language) {
      // Code explanation using real Groq API
      const prompt = `You are an expert ${language} developer and educator. Analyze this ${language} code and provide a clear, educational explanation:

${code}

Please provide:
1. What this code does
2. Key concepts demonstrated
3. Best practices shown or that could be applied
4. Any suggestions for improvement
5. Educational insights for learning ${language}

Keep your response helpful, encouraging, and focused on teaching web development concepts.`;

      const completion = await groq.chat.completions.create({
        messages: [{ role: 'user', content: prompt }],
        model: model || 'llama-3.1-8b-instant',
        temperature: 0.3,
        max_tokens: 1000,
      });

      response = {
        response: completion.choices[0]?.message?.content || 'Unable to generate explanation',
        explanation: `AI-powered analysis of ${language} code`
      };
    } else if (messages && messages.length > 0) {
      // Chat interaction using real Groq API
      const userMessage = messages[messages.length - 1]?.content || '';

      const systemPrompt = `You are Professor Groq, an expert web development educator specializing in HTML, CSS, and JavaScript. Your role is to:

1. Teach web development concepts clearly and patiently
2. Provide practical, working code examples
3. Explain complex topics in simple, digestible steps
4. Encourage best practices and modern techniques
5. Help debug code issues with clear explanations
6. Suggest improvements and optimizations
7. Be encouraging and supportive to learners

Always format your responses with proper markdown, code blocks, and clear structure. Use emojis sparingly but effectively. Focus on being educational and helpful.

Current user question: ${userMessage}`;

      const completion = await groq.chat.completions.create({
        messages: [
          { role: 'system', content: systemPrompt },
          ...messages.slice(-5) // Keep last 5 messages for context
        ],
        model: model || 'llama-3.1-8b-instant',
        temperature: 0.7,
        max_tokens: 1500,
      });

      response = {
        response: completion.choices[0]?.message?.content || 'Unable to generate response',
        choices: [{
          message: {
            content: completion.choices[0]?.message?.content || 'Unable to generate response'
          }
        }]
      };
    } else {
      // Default welcome message using real Groq API
      const welcomePrompt = `You are Professor Groq, a friendly and expert web development educator. Create a welcoming introduction for new students learning HTML, CSS, and JavaScript. Include:

1. A warm greeting
2. What you can help with
3. Available topics
4. Encouragement to start learning

Keep it concise, friendly, and educational.`;

      const completion = await groq.chat.completions.create({
        messages: [{ role: 'user', content: welcomePrompt }],
        model: model || 'llama-3.1-8b-instant',
        temperature: 0.8,
        max_tokens: 500,
      });

      response = {
        response: completion.choices[0]?.message?.content || 'Welcome to KidLearner AI Assistant!',
        choices: [{
          message: {
            content: completion.choices[0]?.message?.content || 'Welcome to KidLearner AI Assistant!'
          }
        }]
      };
    }

    res.json(response);
    let response;

    if (code && language) {
      // Code explanation
      response = {
        response: `AI Analysis for ${language.toUpperCase()}:\n\n${code}\n\n**Key Points:**\n• This code demonstrates ${language} syntax\n• Best practices are followed\n• Consider error handling for production use\n\n**Suggestions:**\n• Add comments for clarity\n• Consider performance optimizations\n• Test edge cases thoroughly`,
        explanation: `Professional code analysis for ${language} code.`
      };
    } else if (messages && messages.length > 0) {
      // Chat interaction
      const userMessage = messages[messages.length - 1]?.content || '';

      if (userMessage.toLowerCase().includes('html')) {
        response = {
          response: "**HTML Best Practices Guide**\n\n**Semantic HTML:**\n• Use `<header>`, `<nav>`, `<main>`, `<section>`, `<article>`, `<aside>`, `<footer>`\n• Choose semantic elements over generic `<div>`\n\n**Accessibility:**\n• Add `alt` attributes to images\n• Use proper heading hierarchy (h1→h2→h3)\n• Ensure sufficient color contrast\n\n**Performance:**\n• Minimize DOM depth\n• Use CSS for styling, not inline styles\n• Optimize images and media\n\n**What specific HTML topic would you like to explore?** 🎯",
          choices: [{
            message: {
              content: "**HTML Best Practices Guide**\n\n**Semantic HTML:**\n• Use `<header>`, `<nav>`, `<main>`, `<section>`, `<article>`, `<aside>`, `<footer>`\n• Choose semantic elements over generic `<div>`\n\n**Accessibility:**\n• Add `alt` attributes to images\n• Use proper heading hierarchy (h1→h2→h3)\n• Ensure sufficient color contrast\n\n**Performance:**\n• Minimize DOM depth\n• Use CSS for styling, not inline styles\n• Optimize images and media\n\n**What specific HTML topic would you like to explore?** 🎯"
            }
          }]
        };
      } else if (userMessage.toLowerCase().includes('css')) {
        response = {
          response: "**CSS Mastery Guide**\n\n**Layout Systems:**\n• **Flexbox**: Perfect for 1D layouts (rows/columns)\n• **Grid**: Powerful for 2D layouts\n• **Floats**: Legacy, avoid for new projects\n\n**Responsive Design:**\n• Mobile-first approach\n• Use `rem`/`em` for scalable typography\n• Media queries for breakpoints\n\n**Modern CSS:**\n• CSS Variables for theming\n• CSS Grid for complex layouts\n• Flexbox for component alignment\n\n**Performance Tips:**\n• Minimize repaints/reflows\n• Use `transform` for animations\n• Optimize selectors\n\n**Which CSS concept interests you most?** 🎨",
          choices: [{
            message: {
              content: "**CSS Mastery Guide**\n\n**Layout Systems:**\n• **Flexbox**: Perfect for 1D layouts (rows/columns)\n• **Grid**: Powerful for 2D layouts\n• **Floats**: Legacy, avoid for new projects\n\n**Responsive Design:**\n• Mobile-first approach\n• Use `rem`/`em` for scalable typography\n• Media queries for breakpoints\n\n**Modern CSS:**\n• CSS Variables for theming\n• CSS Grid for complex layouts\n• Flexbox for component alignment\n\n**Performance Tips:**\n• Minimize repaints/reflows\n• Use `transform` for animations\n• Optimize selectors\n\n**Which CSS concept interests you most?** 🎨"
            }
          }]
        };
      } else if (userMessage.toLowerCase().includes('javascript') || userMessage.toLowerCase().includes('js')) {
        response = {
          response: "**JavaScript Development Guide**\n\n**Core Concepts:**\n• **Variables**: `const`/`let` vs `var`\n• **Functions**: Arrow functions, closures\n• **Objects**: Prototypes, classes\n• **Arrays**: Methods, iteration\n\n**Modern JavaScript:**\n• **ES6+ Features**: Destructuring, spread/rest\n• **Async/Await**: Clean async code\n• **Modules**: Import/export system\n• **Promises**: Async programming\n\n**Best Practices:**\n• Use `const` by default\n• Prefer arrow functions\n• Handle errors properly\n• Write clean, readable code\n\n**Debugging Tips:**\n• Use browser dev tools\n• Console.log strategically\n• Learn debugging techniques\n\n**What JavaScript topic shall we explore?** ⚡",
          choices: [{
            message: {
              content: "**JavaScript Development Guide**\n\n**Core Concepts:**\n• **Variables**: `const`/`let` vs `var`\n• **Functions**: Arrow functions, closures\n• **Objects**: Prototypes, classes\n• **Arrays**: Methods, iteration\n\n**Modern JavaScript:**\n• **ES6+ Features**: Destructuring, spread/rest\n• **Async/Await**: Clean async code\n• **Modules**: Import/export system\n• **Promises**: Async programming\n\n**Best Practices:**\n• Use `const` by default\n• Prefer arrow functions\n• Handle errors properly\n• Write clean, readable code\n\n**Debugging Tips:**\n• Use browser dev tools\n• Console.log strategically\n• Learn debugging techniques\n\n**What JavaScript topic shall we explore?** ⚡"
            }
          }]
        };
      } else {
        response = {
          response: "**Welcome to KidLearner AI Assistant! 🤖**\n\nI'm here to help you learn HTML, CSS, and JavaScript through interactive coding lessons. I can:\n\n**Code Help:**\n• Explain code snippets\n• Debug errors\n• Suggest improvements\n• Teach best practices\n\n**Learning Support:**\n• Answer questions about web development\n• Provide step-by-step tutorials\n• Recommend learning resources\n• Help with projects\n\n**Available Topics:**\n• **HTML**: Structure and semantics\n• **CSS**: Styling and layouts\n• **JavaScript**: Interactivity and logic\n\n**What would you like to learn today?** Feel free to ask me anything about web development! 🚀",
          choices: [{
            message: {
              content: "**Welcome to KidLearner AI Assistant! 🤖**\n\nI'm here to help you learn HTML, CSS, and JavaScript through interactive coding lessons. I can:\n\n**Code Help:**\n• Explain code snippets\n• Debug errors\n• Suggest improvements\n• Teach best practices\n\n**Learning Support:**\n• Answer questions about web development\n• Provide step-by-step tutorials\n• Recommend learning resources\n• Help with projects\n\n**Available Topics:**\n• **HTML**: Structure and semantics\n• **CSS**: Styling and layouts\n• **JavaScript**: Interactivity and logic\n\n**What would you like to learn today?** Feel free to ask me anything about web development! 🚀"
            }
          }]
        };
      }
    } else {
      response = {
        response: "**Welcome to KidLearner AI Assistant! 🤖**\n\nI'm here to help you learn HTML, CSS, and JavaScript through interactive coding lessons. I can:\n\n**Code Help:**\n• Explain code snippets\n• Debug errors\n• Suggest improvements\n• Teach best practices\n\n**Learning Support:**\n• Answer questions about web development\n• Provide step-by-step tutorials\n• Recommend learning resources\n• Help with projects\n\n**Available Topics:**\n• **HTML**: Structure and semantics\n• **CSS**: Styling and layouts\n• **JavaScript**: Interactivity and logic\n\n**What would you like to learn today?** Feel free to ask me anything about web development! 🚀",
        choices: [{
          message: {
            content: "**Welcome to KidLearner AI Assistant! 🤖**\n\nI'm here to help you learn HTML, CSS, and JavaScript through interactive coding lessons. I can:\n\n**Code Help:**\n• Explain code snippets\n• Debug errors\n• Suggest improvements\n• Teach best practices\n\n**Learning Support:**\n• Answer questions about web development\n• Provide step-by-step tutorials\n• Recommend learning resources\n• Help with projects\n\n**Available Topics:**\n• **HTML**: Structure and semantics\n• **CSS**: Styling and layouts\n• **JavaScript**: Interactivity and logic\n\n**What would you like to learn today?** Feel free to ask me anything about web development! 🚀"
          }
        }]
      };
    }

    res.json(response);

  } catch (error) {
    console.error('Groq API Error:', error);
    res.status(500).json({
      error: 'AI Service Error',
      message: 'Unable to process AI request',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

module.exports = router;